on:
  push:
    branches: [ "main" ]

env:
  USER: mingi4754song
  INSTANCE_NAME: server-instance
  ZONE: us-west1-b
  BUILD_RESULT: number_game_session_manager

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - name: Checkout from remote repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: |
          CGO_ENABLED=0 go build -o $BUILD_RESULT .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Transfer to Google Cloud Compute Instance
        run: |
          gcloud compute scp ./$BUILD_RESULT $USER@$INSTANCE_NAME:~/ --zone=$ZONE

      - name: Run Game Server
        run: |
          gcloud compute ssh $USER@$INSTANCE_NAME --zone=$ZONE --command="nohup ./$BUILD_RESULT > ~/session_manager.log 2>&1 & exit"


